image:
    file: .gitpod.dockerfile
ports:
    - port: 5000
      onOpen: open-preview
tasks:
    - name: Redis
      init: gp sync-await bundle # await Rails command
      command: redis-server
      openMode: split-left

    - name: Rails
      init: >
        cp config/database.yml.gitpod config/database.yml &&
        cp config/config.yml.example config/config.yml &&
        cp db/schema.rb.example db/schema.rb &&
        bundle install --without production &&
        yarn install &&
        gp sync-done bundle &&
        rails db:create &&
        rails db:schema:load &&
        rails db:migrate &&
        rake db:fixtures:load # load test data into database
      command: >
        passenger start --port 5000
      openMode: tab-after

    - name: Rails console
      init: gp sync-await bundle # await Rails command
      command: rails c
      openMode: split-right
    
github:
    prebuilds:
        branches: true
        pullRequests: true
        pullRequestsFromForks: true
        addCheck: true
        addComment: true
        addBadge: false
        addLabel: false
