language: ruby

dist: trusty

rvm:
  - 2.6.5

node_js:
  - 13

env:
  global:
    - RAILS_ENV=test
    - DB_HOST='127.0.0.1'
    - DB_USER='swbench'
    - DB_PASS='swbench'
    - DB_NAME='swbench'

cache:
  directories:
   - $PWD/vendor/.bundle/
   - $PWD/public/lib/

services:
  - docker
  - mysql

before_install:
  - cp config/database.yml.example config/database.yml
  - cp config/config.yml.example config/config.yml
  - cp db/schema.rb.example db/schema.rb
  - bundle config set path 'vendor/.bundle/'

install:
  - bundle install
  - npm install -g bower
  - bower install --allow-root
  - if [ $RAILS_ENV == 'production' ]; then
      mysql -e "CREATE DATABASE swbench;";
      mysql -e "CREATE USER 'swbench'@'%' IDENTIFIED BY 'swbench';";
      mysql -e "GRANT ALL PRIVILEGES ON *.* TO 'swbench'@'%';";
      bundle exec rake db:schema:load;
      bundle exec rake db:migrate;
    else
      bundle exec rake db:create;
      bundle exec rake db:schema:load;
      bundle exec rake db:migrate;
    fi

jobs:
  include:
    - name: "Unit Tests"
      script: rake test:units
    - name: "Helpers Tests"
      script: ruby -I test test/unit/helpers/*.rb
    - name: "Functional Tests"
      script: rake test:functionals
    - name: "Integration Tests"
      script: rake test:integration
    - name: "Docker Builds"
      script: docker build -t swbench .
    - name: "Asset Precompilation"
      env:
        - RAILS_ENV=production
      script:
        - bundle exec rake assets:precompile
