version: '3.5'
services:

  db:
    image: mysql:5.7
    env_file:
      - spectral.env
    volumes:
      - mysql_data:/var/lib/mysql

  web:
    build: .
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
    env_file:
      - spectral.env
    environment:
      - PORT=${PORT}    
    ports:
      - 127.0.0.1:${PORT:-5000}:${PORT:-5000}
    depends_on:
      - db

volumes:
  mysql_data:
  bundle_cache:
