version: '3.5'
services:

  db:
    container_name: spectral-db
    image: mysql:5.7
    env_file:
      - spectral.env
    volumes:
      - mysql_data:/var/lib/mysql

  web:
    container_name: spectral-web
    build: .
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
    env_file:
      - spectral.env
    ports:
      - 5000:5000
    depends_on:
      - db

volumes:
  mysql_data:
  bundle_cache:
